### ISSUE TITLE
A typo in some errors descriptions

### ISSUE THREAD

**Issue by grrrammarnazi20** [MinterTeam/minter-console-web#15]
There is a typo in the word "Минимальнцая"

https://github.com/MinterTeam/minter-console-web/blob/a00f236ad32e4133793e6e6d50c4bbce1537348a/lang/ru.js#L349

https://github.com/MinterTeam/minter-console-web/blob/a00f236ad32e4133793e6e6d50c4bbce1537348a/lang/ru.js#L352

**Comment by shrpne** [comment]
Thanks! I will fix it in the next release.

**Comment by shrpne** [comment]
Done
