### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by HarpyWar** [MinterTeam/minter-console-web#7]
Make it possible to change listening port, something like this:
`minter-console-0.3.0-portable-x64.exe -port 8000`

Port 4000 is busy on my machine by `svchost.exe`

**Comment by shrpne** [comment]
Please try `minter-console-0.3.0-portable-x64.exe -- --port=8000`
Available commands, for now, are: `port` and `hostname`

**Comment by HarpyWar** [comment]
It works, thanks.
